spring:
  datasource:
    username: root
    password: wcjb
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manager?characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8&useSSL=false
  mvc:
    view:
      suffix: .jsp
      prefix: /jsp/
mybatis:
   mapper-locations: classpath:mybatisConf/mapper/*.xml

