package com.zjt.manager.mapper;

import com.zjt.manager.pojo.Roleau;
import com.zjt.manager.pojo.RoleauExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleauMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleau
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int countByExample(RoleauExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleau
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int deleteByExample(RoleauExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleau
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int insert(Roleau record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleau
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int insertSelective(Roleau record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleau
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    List<Roleau> selectByExample(RoleauExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleau
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int updateByExampleSelective(@Param("record") Roleau record, @Param("example") RoleauExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleau
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int updateByExample(@Param("record") Roleau record, @Param("example") RoleauExample example);
}