package com.zjt.manager.mapper;

import com.zjt.manager.pojo.Score;
import com.zjt.manager.pojo.ScoreExample;
import java.util.List;

import com.zjt.manager.pojo.result.ScoreResult;
import com.zjt.manager.pojo.search.SearchCriteron;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    long countByExample(ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    int deleteByExample(ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    int deleteByPrimaryKey(Integer scoreid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    int insert(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    int insertSelective(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    List<Score> selectByExample(ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    Score selectByPrimaryKey(Integer scoreid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") Score record, @Param("example") ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    int updateByExample(@Param("record") Score record, @Param("example") ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    int updateByPrimaryKeySelective(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    int updateByPrimaryKey(Score record);

    List<Score> selectByLimit(Integer page, Integer limit);

    List<Score> selectByCriteron(String sname);

    List<ScoreResult> selectByProject(SearchCriteron search);


    List<ScoreResult> selectAllByProject(SearchCriteron search);
}