package com.zjt.manager.mapper;

import com.zjt.manager.pojo.Term;
import com.zjt.manager.pojo.TermExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TermMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int countByExample(TermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int deleteByExample(TermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int deleteByPrimaryKey(Integer ctid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int insert(Term record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int insertSelective(Term record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    List<Term> selectByExample(TermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    Term selectByPrimaryKey(Integer ctid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int updateByExampleSelective(@Param("record") Term record, @Param("example") TermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int updateByExample(@Param("record") Term record, @Param("example") TermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int updateByPrimaryKeySelective(Term record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table term
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int updateByPrimaryKey(Term record);
}