package com.zjt.manager.mapper;

import com.zjt.manager.pojo.Urole;
import com.zjt.manager.pojo.UroleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urole
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int countByExample(UroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urole
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int deleteByExample(UroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urole
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int insert(Urole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urole
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int insertSelective(Urole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urole
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    List<Urole> selectByExample(UroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urole
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int updateByExampleSelective(@Param("record") Urole record, @Param("example") UroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urole
     *
     * @mbggenerated Sat Jan 11 16:19:10 CST 2020
     */
    int updateByExample(@Param("record") Urole record, @Param("example") UroleExample example);
}