package com.zjt.manager.pojo;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cid
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cname
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.tid
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.ctname
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    private String ctname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cid
     *
     * @return the value of course.cid
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cid
     *
     * @param cid the value for course.cid
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cname
     *
     * @return the value of course.cname
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cname
     *
     * @param cname the value for course.cname
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.tid
     *
     * @return the value of course.tid
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.tid
     *
     * @param tid the value for course.tid
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.ctname
     *
     * @return the value of course.ctname
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    public String getCtname() {
        return ctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.ctname
     *
     * @param ctname the value for course.ctname
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    public void setCtname(String ctname) {
        this.ctname = ctname == null ? null : ctname.trim();
    }
}