package com.zjt.manager.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Score {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.scoreid
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    private Integer scoreid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.sid
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.tid
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.cid
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.score
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.sname
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.lname
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    private String lname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.cdate
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")
    private Date cdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.scoreid
     *
     * @return the value of score.scoreid
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    public Integer getScoreid() {
        return scoreid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.scoreid
     *
     * @param scoreid the value for score.scoreid
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    public void setScoreid(Integer scoreid) {
        this.scoreid = scoreid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.sid
     *
     * @return the value of score.sid
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.sid
     *
     * @param sid the value for score.sid
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.tid
     *
     * @return the value of score.tid
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.tid
     *
     * @param tid the value for score.tid
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.cid
     *
     * @return the value of score.cid
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.cid
     *
     * @param cid the value for score.cid
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.score
     *
     * @return the value of score.score
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.score
     *
     * @param score the value for score.score
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.sname
     *
     * @return the value of score.sname
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.sname
     *
     * @param sname the value for score.sname
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.lname
     *
     * @return the value of score.lname
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    public String getLname() {
        return lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.lname
     *
     * @param lname the value for score.lname
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    public void setLname(String lname) {
        this.lname = lname == null ? null : lname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.cdate
     *
     * @return the value of score.cdate
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    public Date getCdate() {
        return cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.cdate
     *
     * @param cdate the value for score.cdate
     *
     * @mbg.generated Sun Jan 19 11:08:11 CST 2020
     */
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }

    @Override
    public String toString() {
        return "Score{" +
                "scoreid=" + scoreid +
                ", sid=" + sid +
                ", tid=" + tid +
                ", cid=" + cid +
                ", score=" + score +
                ", sname='" + sname + '\'' +
                ", lname='" + lname + '\'' +
                ", cdate=" + cdate +
                '}';
    }
}