package com.zjt.manager.pojo;

import java.util.Date;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sid
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sname
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sgender
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    private String sgender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.school
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.grade
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.address
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.pname
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.tel
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.cid
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.edate
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    private Date edate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sid
     *
     * @return the value of student.sid
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sid
     *
     * @param sid the value for student.sid
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sname
     *
     * @return the value of student.sname
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sname
     *
     * @param sname the value for student.sname
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sgender
     *
     * @return the value of student.sgender
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    public String getSgender() {
        return sgender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sgender
     *
     * @param sgender the value for student.sgender
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    public void setSgender(String sgender) {
        this.sgender = sgender == null ? null : sgender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.school
     *
     * @return the value of student.school
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.school
     *
     * @param school the value for student.school
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.grade
     *
     * @return the value of student.grade
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.grade
     *
     * @param grade the value for student.grade
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.address
     *
     * @return the value of student.address
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.address
     *
     * @param address the value for student.address
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.pname
     *
     * @return the value of student.pname
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.pname
     *
     * @param pname the value for student.pname
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.tel
     *
     * @return the value of student.tel
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.tel
     *
     * @param tel the value for student.tel
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.cid
     *
     * @return the value of student.cid
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.cid
     *
     * @param cid the value for student.cid
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.edate
     *
     * @return the value of student.edate
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    public Date getEdate() {
        return edate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.edate
     *
     * @param edate the value for student.edate
     *
     * @mbg.generated Sun Jan 26 10:31:24 CST 2020
     */
    public void setEdate(Date edate) {
        this.edate = edate;
    }
}