package com.zjt.manager.pojo;

import java.util.Date;

public class Term {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term.ctid
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    private Integer ctid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term.cdate
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    private Date cdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term.ctname
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    private String ctname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term.ctid
     *
     * @return the value of term.ctid
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    public Integer getCtid() {
        return ctid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term.ctid
     *
     * @param ctid the value for term.ctid
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    public void setCtid(Integer ctid) {
        this.ctid = ctid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term.cdate
     *
     * @return the value of term.cdate
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    public Date getCdate() {
        return cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term.cdate
     *
     * @param cdate the value for term.cdate
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term.ctname
     *
     * @return the value of term.ctname
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    public String getCtname() {
        return ctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term.ctname
     *
     * @param ctname the value for term.ctname
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    public void setCtname(String ctname) {
        this.ctname = ctname == null ? null : ctname.trim();
    }
}