package com.zjt.manager.pojo;

public class Urole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urole.uid
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urole.roleid
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urole.uid
     *
     * @return the value of urole.uid
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urole.uid
     *
     * @param uid the value for urole.uid
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urole.roleid
     *
     * @return the value of urole.roleid
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urole.roleid
     *
     * @param roleid the value for urole.roleid
     *
     * @mbggenerated Sat Jan 11 16:28:52 CST 2020
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}